{{- if .Values.postgres.enabled -}}
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ include "nodejs-api.fullname" . }}-db
  labels:
    {{- include "nodejs-api.labels" . | nindent 4 }}
spec:
  instances: {{ .Values.postgres.replicaCount }}
  storage:
    size: {{ .Values.postgres.storage.size }}
  monitoring:
    enablePodMonitor: true
{{- end }}
