{{- if .Values.ingress.enabled -}}
{{- $fullname := include "nodejs-api.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullname }}
  labels:
    {{- include "nodejs-api.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  tls:
    - hosts:
      - api.{{ (lookup "v1" "ConfigMap" "default" "domain").data.domain }}
      secretName: {{ $fullname }}-tls
  rules:
    - host: api.{{ (lookup "v1" "ConfigMap" "default" "domain").data.domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ $fullname }}
                port:
                  number: {{ $svcPort }}
{{- end }}
