apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ include "nodejs-api.fullname" . }}
spec:
  selector:
    matchLabels:
      "app.kubernetes.io/name": {{ include "nodejs-api.fullname" . }}
  podMetricsEndpoints:
  - port: api
    path: /metrics
