---
alertmanager:
  enabled: true
  alertmanagerSpec:
    storage:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 16Gi

  config:
    global:
      resolve_timeout: 5m
    templates:
      - '/etc/alertmanager/config/*.tmpl'

  ingress:
    enabled: false

grafana:
  enabled: true

  grafana.ini:
    server:
      domain: ${grafana_host}
      root_url: "%(protocol)s://%(domain)s/"
    alerting:
      enabled: false
    unified_alerting:
      enabled: true
    users:
      auto_assign_org_role: "Editor"
  additionalDataSources:
    - name: Jaeger
      type: jaeger
      url: https://jaeger-query.monitoring:16686
  persistence:
    type: pvc
    enabled: true

  plugins:
    - grafana-piechart-panel
    - grafana-clock-panel

  ingress:
    enabled: true
    annotations:
      "acme.cert-manager.io/http01-edit-in-place": "true"
      "kubernetes.io/ingress.class": "nginx"
      "kubernetes.io/tls-acme": "true"
      "cert-manager.io/cluster-issuer": "letsencrypt"
    hosts: ["${grafana_host}"]
    pathType: Prefix
    tls:
      - secretName: grafana-general-tls
        hosts: ["${grafana_host}"]

prometheus:
  enabled: true

  prometheusSpec:
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 32Gi
    shards: 1
    probeSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    serviceMonitorSelectorNilUsesHelmValues: false

  thanosIngress:
    enabled: false

  ingress:
    enabled: false

prometheus-node-exporter:
  service:
    port: 30206
    targetPort: 30206

kubeEtcd:
  enabled: false

kubeControllerManager:
  enabled: false

kubeScheduler:
  enabled: false
