# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
provider "kubernetes" {
  config_path    = "/Users/bustnetlight.com/src/ultimate-k8s/infrastructure/config"
}

provider "helm" {
  kubernetes {
    config_path    = "/Users/bustnetlight.com/src/ultimate-k8s/infrastructure/config"
  }
}
