# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
provider "kubernetes" {
  config_path    = "/Users/bustnetlight.com/src/ultimate-k8s/infrastructure/config"
  config_context = "prod-k8s-1"
}

provider "helm" {
  kubernetes {
    config_path    = "/Users/bustnetlight.com/src/ultimate-k8s/infrastructure/config"
    config_context = "prod-k8s-1"
  }
}
